version: 1.0.{build}
configuration: Release
before_build:
- ps: >-
    (new-object net.webclient).DownloadFile('https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-win-x64.latest.exe','core.exe')

    core.exe /install /quiet /norestart

    dotnet restore
build_script:
- cmd: dotnet build src\WebApiContrib.Core.Concurrency
test_script:
- cmd: dotnet test tests\WebApiContrib.Core.Concurrency.Tests