image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
build_script:
- build.bat Build
before_build:
- appveyor-retry dotnet restore -v Minimal
test_script:
- build.bat Test