image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
build_script:
- dotnet build
- dotnet build src\WebApiContrib.Core.Concurrency
before_build:
- appveyor-retry dotnet restore -v Minimal
test_script:
- cd tests/WebApiContrib.Core.Concurrency.Tests
- dotnet test
- cd ../../tests/WebApiContrib.Core.Protobuf.Tests
- dotnet test