image: Visual Studio 2017 RC
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
build_script:
- dotnet build
- dotnet build src\WebApiContrib.Core.Concurrency
init:
- git config --global core.autocrlf true
before_build:
- appveyor-retry dotnet restore -v Minimal
test_script:
- dotnet test tests\WebApiContrib.Core.Concurrency.Tests